name: Publish Packages to Nuget

on:
  workflow_dispatch:
     inputs:
      core-version:
         type: string
         required: true
      main-version:
        type: string
        required: true

permissions:
  contents: read

jobs:
  build-and-publish:
      runs-on: ubuntu-latest
  
      permissions:
        id-token: write 
      environment: production
        
      steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/CliInvoke.Core
      - name: Create packages
        run: dotnet build -c Release
        working-directory: src/CliInvoke.Core
        
          # Get a short-lived NuGet API key
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.1.0
        id: login
        with:
            user: ${{ secrets.NUGET_USER }}
              
          # Push the Core package
      - name: NuGet push
        run: dotnet nuget push src/CliInvoke.Core/bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Sleep for 300 seconds
        run: sleep 300s
        shell: bash
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/CliInvoke.Specializations
      - name: Create packages
        run: dotnet build -c Release -p:UsePublishedPackages=true -p:CliInvokeCoreVersion=${{ inputs.core-version }}
        working-directory: src/CliInvoke.Specializations
        # Push the Specializations package
      - name: NuGet push
        run: dotnet nuget push src/CliInvoke.Specializations/bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/CliInvoke
      - name: Create packages
        run: dotnet build -c Release -p:UsePublishedPackages=true -p:CliInvokeCoreVersion=${{ inputs.core-version }} 
        working-directory: src/CliInvoke

      # Push the Main package
      - name: NuGet push
        run: dotnet nuget push src/CliInvoke/bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Sleep for 300s seconds
        run: sleep 300s
        shell: bash
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/CliInvoke.Extensions
      - name: Create packages
        run: dotnet build -c Release -p:UsePublishedPackages=true -p:CliInvokeCoreVersion=${{ inputs.core-version }} -p:CliInvokeVersion=${{ inputs.main-version }}
        working-directory: src/CliInvoke.Extensions

        # Push the Extensions package
      - name: NuGet push
        run: dotnet nuget push src/CliInvoke.Extensions/bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

